# code: language=ansible
---
- name: Restart containerd
  listen: containerd_restart
  ansible.builtin.service:
    name: containerd
    state: restarted

- name: Reload sysctl
  listen: sysctl_reload
  ansible.builtin.command:
    cmd: sysctl --system
  changed_when: false
